/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mateo
 */
public class View extends javax.swing.JFrame {
     DefaultTableModel tableModel;
    /**
     * Creates new form ControlJList
     */
    
    public View() {
        initComponents();
        setearComandosBotones();
        setearTabla();
        setVisible(true);
        setTitle("Ejercicio 7 componente JList");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelModelo = new javax.swing.JLabel();
        JTextModelo = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        JTextCor = new javax.swing.JTextField();
        JTextAncho = new javax.swing.JTextField();
        jLabelAncho = new javax.swing.JLabel();
        JTextAlto = new javax.swing.JTextField();
        jLabelAlto = new javax.swing.JLabel();
        jLabelCm = new javax.swing.JLabel();
        jLabelAltoCm = new javax.swing.JLabel();
        jButtonEngadir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonInformacion = new javax.swing.JButton();
        jButtonEliminarAlfombra = new javax.swing.JButton();
        jButtonEliminarTodas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova alfombra"));

        jLabelModelo.setText("Modelo");

        JTextModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextModeloActionPerformed(evt);
            }
        });

        jLabelCor.setText("Cor");

        JTextCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextCorActionPerformed(evt);
            }
        });

        JTextAncho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextAnchoActionPerformed(evt);
            }
        });

        jLabelAncho.setText("Ancho");

        JTextAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextAltoActionPerformed(evt);
            }
        });

        jLabelAlto.setText("Alto");

        jLabelCm.setText("(cm)");

        jLabelAltoCm.setText("(cm)");

        jButtonEngadir.setText("Engadir");
        jButtonEngadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEngadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextCor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAncho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAlto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAltoCm)))
                .addGap(12, 12, 12)
                .addComponent(jButtonEngadir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo)
                    .addComponent(JTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEngadir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAlto)
                        .addComponent(JTextAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCm)
                        .addComponent(jLabelAltoCm))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAncho)
                        .addComponent(JTextAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCor)
                        .addComponent(JTextCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alfombras dispoñibles"));

        jButtonInformacion.setText("Información das alfombras");
        jButtonInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformacionActionPerformed(evt);
            }
        });

        jButtonEliminarAlfombra.setText("Eliminar alfombra");
        jButtonEliminarAlfombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAlfombraActionPerformed(evt);
            }
        });

        jButtonEliminarTodas.setText("Eliminar todas");
        jButtonEliminarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTodasActionPerformed(evt);
            }
        });

        javax.swing.table.DefaultTableModel modeloTabla = new DefaultTableModel();
        jTable2.setModel(modeloTabla);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInformacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarAlfombra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarTodas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonInformacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarAlfombra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarTodas))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextModeloActionPerformed

    private void JTextCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextCorActionPerformed

    private void JTextAnchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextAnchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextAnchoActionPerformed

    private void JTextAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextAltoActionPerformed

    private void jButtonEngadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEngadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEngadirActionPerformed

    private void jButtonInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInformacionActionPerformed

    private void jButtonEliminarAlfombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAlfombraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarAlfombraActionPerformed

    private void jButtonEliminarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTodasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarTodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextAlto;
    private javax.swing.JTextField JTextAncho;
    private javax.swing.JTextField JTextCor;
    private javax.swing.JTextField JTextModelo;
    private javax.swing.JButton jButtonEliminarAlfombra;
    private javax.swing.JButton jButtonEliminarTodas;
    private javax.swing.JButton jButtonEngadir;
    private javax.swing.JButton jButtonInformacion;
    private javax.swing.JLabel jLabelAlto;
    private javax.swing.JLabel jLabelAltoCm;
    private javax.swing.JLabel jLabelAncho;
    private javax.swing.JLabel jLabelCm;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void setearComandosBotones() {
        /*
        Le decimos a cada boton como se va a llamar, esto es importante para que el escuchador ( controller en nuestro caso)
        sepa que boton estamos pulsando y actue en consecuencia
        */
        jButtonEngadir.setActionCommand("engadir");
        jButtonEliminarTodas.setActionCommand("eliminarTodas");
        jButtonEliminarAlfombra.setActionCommand("eliminarAlfombra");
        jButtonInformacion.setActionCommand("mostrasInformacion");   
    }

    //Getters de los botones para codificar cada accion para el escuchador ( clase controller )
    
    
    public JButton getjButtonEliminarAlfombra() {
        return this.jButtonEliminarAlfombra;
    }

    public JButton getjButtonEliminarTodas() {
        return this.jButtonEliminarTodas;
    }

    public JButton getjButtonEngadir() {
        return this.jButtonEngadir;
    }

    public JButton getjButtonInformacion() {
        return this.jButtonInformacion;
    }

    public JTextField getJTextAlto() {
        return this.JTextAlto;
    }

    public JTextField getJTextAncho() {
        return this.JTextAncho;
    }

    public JTextField getJTextCor() {
        return this.JTextCor;
    }

    public JTextField getJTextModelo() {
        return this.JTextModelo;
    }

    public void setJTextAlto(JTextField JTextAlto) {
        this.JTextAlto = JTextAlto;
    }

    public void setJTextAncho(JTextField JTextAncho) {
        this.JTextAncho = JTextAncho;
    }

    public void setJTextCor(JTextField JTextCor) {
        this.JTextCor = JTextCor;
    }

    public void setJTextModelo(JTextField JTextModelo) {
        this.JTextModelo = JTextModelo;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }  

    public DefaultTableModel getTableModel() {
        return tableModel;
    }

    public void setTableModel(DefaultTableModel tableModel) {
        this.tableModel = tableModel;
    }
    

    private void setearTabla() {
        tableModel = new DefaultTableModel();
        String [] cabecera = {"Nombre","Color","Ancho","Alto"};
        tableModel.setColumnIdentifiers(cabecera);
        jTable2.setModel(tableModel);
    }

    

    
}
