/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.awt.event.ActionListener;
import javax.swing.JDesktopPane;

/**
 *
 * @author a22mateoca
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Controlador controlador;
    private VentanaAñadirDirector vad;
    private VentanaEliminarDirector ved;
    
    private VentanaAñadirGenero vag;
    private VentanaEliminarGenero veg;
    
    private VentanaGestionPeliculas vgp;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
        añadirEscuchador();
    }

    private void añadirEscuchador() {
        añadirDirector.addActionListener((ActionListener)controlador);
        añadirDirector.setActionCommand("añadirDirector");
        eliminarDirector.addActionListener((ActionListener)controlador);
        eliminarDirector.setActionCommand("eliminarDirector");
        añadirGenero.addActionListener((ActionListener)controlador);
        añadirGenero.setActionCommand("añadirGenero");
        eliminarGenero.addActionListener((ActionListener)controlador);
        eliminarGenero.setActionCommand("eliminarGenero");
        añadirPelicula.addActionListener((ActionListener)controlador);
        añadirPelicula.setActionCommand("añadirPelicula");
        eliminarPelicula.addActionListener((ActionListener)controlador);
        eliminarPelicula.setActionCommand("eliminarPelicula");
    }

    public void setVad(VentanaAñadirDirector ventana) {
        this.vad = ventana;
        vad.setBounds(10, 10, 200, 200);
        vad.setVisible(true);
        jDesktopPane1.add(this.vad);
        this.vad.getjButton1().addActionListener(controlador);
        this.vad.getjButton1().setActionCommand("botonInternalFrameAñadirDirector");
        añadirDirector.setActionCommand("añadirDirector");
    }
    
    public VentanaAñadirDirector getVad() {
        return vad;
    }
    
    public void setVed(VentanaEliminarDirector ventana) {
        eliminarDirector.setActionCommand("eliminarDirector");
        ved = ventana;
        ved.setBounds(50, 10, 600, 400);
        ved.setVisible(true);
        jDesktopPane1.add(ved);
        ved.getEliminarDirector().addActionListener(controlador);
        ved.getEliminarDirector().setActionCommand("botonInternalFrameEliminarDirector");
    }
    
    public VentanaEliminarDirector getVed() {
        return ved;
    }
    
    public void setVag(VentanaAñadirGenero ventana) {
        añadirGenero.setActionCommand("añadirGenero");
        vag = ventana;
        vag.setBounds(80, 10, 600, 400);
        vag.setVisible(true);
        jDesktopPane1.add(vag);
        vag.getBotonAñadirGenero().addActionListener(controlador);
        vag.getBotonAñadirGenero().setActionCommand("botonInternalFrameAgregarGenero");
    }
    
    public VentanaAñadirGenero getVag() {
        return vag;
    }
    
    public void setVeg(VentanaEliminarGenero ventana) {
        eliminarGenero.setActionCommand("eliminarGenero");
        veg = ventana;
        veg.setBounds(80, 10, 600, 400);
        veg.setVisible(true);
        jDesktopPane1.add(veg);
        veg.getBotonEliminar().addActionListener(controlador);
        veg.getBotonEliminar().setActionCommand("botonInternalFrameEliminarGenero");
    }
    
    public VentanaEliminarGenero getVeg() {
        return veg;
    }
    
    public void setVgp(VentanaGestionPeliculas ventana) {
        añadirPelicula.setActionCommand("añadirPelicula");
        vgp = ventana;
        vgp.setBounds(100, 80, 800, 800);
        vgp.setVisible(true);
        jDesktopPane1.add(vgp);
        vgp.getBotonAñadirPelicula().addActionListener(controlador);
        vgp.getBotonEliminar().setActionCommand("botonInternalFrameAgregarPelicula");
        
        vgp.getBotonEliminar().addActionListener(controlador);
        vgp.getBotonEliminar().setActionCommand("botonInternalFrameEliminarPelicula");
    }
    
    public VentanaGestionPeliculas getVgp() {
        return vgp;
    }
    

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        añadirDirector = new javax.swing.JMenuItem();
        eliminarDirector = new javax.swing.JMenuItem();
        añadirGenero = new javax.swing.JMenuItem();
        eliminarGenero = new javax.swing.JMenuItem();
        añadirPelicula = new javax.swing.JMenuItem();
        eliminarPelicula = new javax.swing.JMenuItem();
        añadirPeliculaFavoritos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        jMenu2.setText("Gestion Datos\n");

        añadirDirector.setText("Añadir Director");
        jMenu2.add(añadirDirector);

        eliminarDirector.setText("Eliminar director");
        eliminarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDirectorActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarDirector);

        añadirGenero.setText("Añadir Genero");
        jMenu2.add(añadirGenero);

        eliminarGenero.setText("Eliminar Genero");
        jMenu2.add(eliminarGenero);

        añadirPelicula.setText("Añadir Pelicula");
        añadirPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirPeliculaActionPerformed(evt);
            }
        });
        jMenu2.add(añadirPelicula);

        eliminarPelicula.setText("Eliminar pelicula");
        jMenu2.add(eliminarPelicula);

        añadirPeliculaFavoritos.setText("Añadir pelicula favorita");
        añadirPeliculaFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirPeliculaFavoritosActionPerformed(evt);
            }
        });
        jMenu2.add(añadirPeliculaFavoritos);

        menuPrincipal.add(jMenu2);

        jMenu3.setText("Edit");
        menuPrincipal.add(jMenu3);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarDirectorActionPerformed

    private void añadirPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirPeliculaActionPerformed

    private void añadirPeliculaFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirPeliculaFavoritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirPeliculaFavoritosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem añadirDirector;
    private javax.swing.JMenuItem añadirGenero;
    private javax.swing.JMenuItem añadirPelicula;
    private javax.swing.JMenuItem añadirPeliculaFavoritos;
    private javax.swing.JMenuItem eliminarDirector;
    private javax.swing.JMenuItem eliminarGenero;
    private javax.swing.JMenuItem eliminarPelicula;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables

}
