/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.entregable_3_1.vista;

/**
 *
 * @author mateo
 */
public class VentanaCreditos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCreditos
     */
    public VentanaCreditos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAgradecimientos = new javax.swing.JLabel();

        setTitle("Creditos");

        jLabelAgradecimientos.setText("<html>Este juego es una tarea entregable de la materia de desarrolo de interfaces desarrollada por Mateo Carballo y Luis <br/> En ella presentamos un juego de memoria para demostrar los conocimientos adquiridos en la materia. <br/> Para esto usaremos varios internal frames para cada una de las funcionalidades. Los usuarios de la app deberan registrarse a traves de un formulario.<br/> Una vez registrados deberán introducir sus credenciales para acceder al juego y poder guardar así sus registros<br/> Si quieres profundizar mas en detalle sobre como jugar ve a la sección de ayuda en ella encontrás un apartado explicando en que consiste el juego</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAgradecimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAgradecimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAgradecimientos;
    // End of variables declaration//GEN-END:variables
}
